### ISSUE TITLE
Parameter mismatch in crane-transfer-pvc from UI

### ISSUE THREAD

**Issue by JaydipGabani** [konveyor/crane-ui-plugin#80]
When you try to migrate an application with PVC the following error comes up in `transfer-pvc` task

```
invalid input params for task crane-transfer-pvc: didn't need these params but they were provided anyway: [dest-pvc-capacity]
```

Cause of the error seem to be a parameter mismatch [here](https://github.com/konveyor/crane-ui-plugin/blob/main/src/api/pipelineTaskHelpers.ts#L153) which should be [this](https://github.com/konveyor/crane-runner/blob/main/config/clustertasks/crane-transfer-pvc.yaml#L51).

**Comment by mturley** [comment]
Looks like this was fixed by #82
