### ISSUE TITLE
crane-ownership-change has been removed but it's still being configured by the UI

### ISSUE THREAD

**Issue by jmontleon** [konveyor/crane-ui-plugin#92]
The code that references this task should be removed.

**Comment by mturley** [comment]
@jmontleon it looks like when this task was removed the intention was that the removal is temporary and it should be restored when the ClusterTask implementation is complete. See https://github.com/konveyor/crane-ui-plugin/pull/64

@pranavgaikwad do you know if that's still true? If we intend to restore this task I think we should leave the existing configuration in place so it's easier to re-enable.
